version: '3.7'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
    restart: always
    labels:
      - "docker.group=monitoring"
  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=rooms
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=influxdb_admin
      - INFLUXDB_ADMIN_PASSWORD=influxdb_password
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    ports:
      - '8086:8086'
    restart: always
    volumes:
      - influxdb-storage:/var/lib/influxdb
    labels:
      - "docker.group=monitoring"
  telegraf:
    image: sebd/telegraf-rpi:latest
    command: -config-directory /etc/telegraf/telegraf.d
    privileged: true
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    restart: always
    volumes:
     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /:/rootfs:ro
    labels:
      - "docker.group=monitoring"
  grafana:
    image: grafana/grafana:7.0.1
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=ryantxu-ajax-panel
    ports:
      - '80:3000'
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    labels:
      - "docker.group=monitoring"

volumes:
  influxdb-storage:
    external:
      name: monitoring-influxdb-storage
  grafana-storage:
    external:
      name: monitoring-grafana-storage
